#!/bin/sh


DEFAULT_WORKERS=$((2 * $(nproc) + 1))
DEFAULT_WORKER_CLASS="uvicorn.workers.UvicornWorker"
DEFAULT_SOCKET_PATH="unix:/tmp/gunicorn_socket/gunicorn.sock"
DEFAULT_LOG_LEVEL="error"
DEFAULT_ERROR_LOG_FILE="-"
DEFAULT_ACCESS_LOG_FILE="-"
DEFAULT_CAPTURE_OUTPUT="false"
DEFAULT_KEEP_ALIVE="5"
DEFAULT_TIMEOUT="30"
DEFAULT_LOGGER="app.logger.GunicornLogger"
DEFAULT_FORWARDED_ALLOW_IPS=$(getent hosts nginx | awk '{ print $1 }')




GUNICORN_WORKERS=${GUNICORN_WORKERS:-$DEFAULT_WORKERS}
GUNICORN_SOCKET_PATH=${GUNICORN_SOCKET_PATH:-$DEFAULT_SOCKET_PATH}
GUNICORN_WORKER_CLASS=${GUNICORN_WORKER_CLASS:-$DEFAULT_WORKER_CLASS}
GUNICORN_LOG_LEVEL=${GUNICORN_LOG_LEVEL:-$DEFAULT_LOG_LEVEL}
GUNICORN_ERROR_LOG_FILE=${GUNICORN_ERROR_LOG_FILE:-$DEFAULT_ERROR_LOG_FILE}
GUNICORN_ACCESS_LOG_FILE=${GUNICORN_ACCESS_LOG_FILE:-$DEFAULT_ACCESS_LOG_FILE}
GUNICORN_CAPTURE_OUTPUT=${GUNICORN_CAPTURE_OUTPUT:-$DEFAULT_CAPTURE_OUTPUT}
GUNICORN_KEEP_ALIVE=${GUNICORN_KEEP_ALIVE:-$DEFAULT_KEEP_ALIVE}
GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-$DEFAULT_TIMEOUT}
GUNICORN_LOGGER=${GUNICORN_LOGGER:-$DEFAULT_LOGGER}
GUNICORN_FORWARDED_ALLOW_IPS=${GUNICORN_FORWARDED_ALLOW_IPS:-$DEFAULT_FORWARDED_ALLOW_IPS}

